from __future__ import annotations

from dataclasses import dataclass


DEFAULT_BASELINE_LATENCY_MS = 50.0
BASELINE_WINDOW = 10
ACTION_TIMEOUT_SECONDS = 8.0

REDOS_LATENCY_THRESHOLD_MS = 1500.0
DB_TIMEOUT_THRESHOLD_MS = 800.0

CHAIN_REQUIRED_ORDERS = 21
CHAIN_COOLDOWN_STEPS = 10

STEP_DELTA_MAX = 0.30
NEW_ENDPOINT_BONUS = 0.05
NEW_VULNERABILITY_BONUS = 0.10
REPEATED_ACTION_PENALTY = 0.02
TERMINAL_BONUS = 0.20

EARLY_TERMINATION_REWARD = -200.0


@dataclass(frozen=True)
class RewardConstants:
    DEFAULT_BASELINE_LATENCY_MS: float = DEFAULT_BASELINE_LATENCY_MS
    BASELINE_WINDOW: int = BASELINE_WINDOW
    ACTION_TIMEOUT_SECONDS: float = ACTION_TIMEOUT_SECONDS
    REDOS_LATENCY_THRESHOLD_MS: float = REDOS_LATENCY_THRESHOLD_MS
    DB_TIMEOUT_THRESHOLD_MS: float = DB_TIMEOUT_THRESHOLD_MS
    CHAIN_REQUIRED_ORDERS: int = CHAIN_REQUIRED_ORDERS
    CHAIN_COOLDOWN_STEPS: int = CHAIN_COOLDOWN_STEPS
    STEP_DELTA_MAX: float = STEP_DELTA_MAX
    NEW_ENDPOINT_BONUS: float = NEW_ENDPOINT_BONUS
    NEW_VULNERABILITY_BONUS: float = NEW_VULNERABILITY_BONUS
    REPEATED_ACTION_PENALTY: float = REPEATED_ACTION_PENALTY
    TERMINAL_BONUS: float = TERMINAL_BONUS
    EARLY_TERMINATION_REWARD: float = EARLY_TERMINATION_REWARD
